'use client';

import { useCallback, useEffect, useState } from 'react';
import { reportReasonLabels, sectionLabels, type CommunitySection } from '@/lib/community/types';
import type { AdminCommunityItem } from '@/lib/server/community';

const statusOptions = [['', 'Todos'], ['active', 'Activos'], ['hidden', 'Ocultos'], ['deleted', 'Eliminados'], ['deleted_by_author', 'Eliminados por autor']] as const;
const sectionOptions: Array<['' | CommunitySection, string]> = [['', 'Todas las secciones'], ...Object.entries(sectionLabels) as Array<[CommunitySection, string]>];

export function AdminCommunity() {
  const [items, setItems] = useState<AdminCommunityItem[]>([]); const [status, setStatus] = useState(''); const [section, setSection] = useState(''); const [reported, setReported] = useState(true); const [date, setDate] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [expanded, setExpanded] = useState<string | null>(null);
  const load = useCallback(async () => { setBusy(true); setMessage(''); try { const query = new URLSearchParams({ ...(status ? { status } : {}), ...(section ? { section } : {}), ...(date ? { after: new Date(`${date}T00:00:00`).toISOString() } : {}), reported: String(reported), lessonId: '1' }); const response = await fetch(`/api/admin/community?${query}`, { cache: 'no-store' }); const body = await response.json() as AdminCommunityItem[] & { error?: string }; if (!response.ok) throw new Error(body.error ?? 'No se pudo cargar moderación.'); setItems(body); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo cargar moderación.'); } finally { setBusy(false); } }, [date, reported, section, status]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function moderate(item: AdminCommunityItem, action: 'hide' | 'restore' | 'delete' | 'ban' | 'unban') {
    const reason = action === 'restore' || action === 'unban' ? '' : window.prompt(action === 'ban' ? 'Motivo del bloqueo de publicaciones:' : 'Motivo de moderación:') ?? '';
    if (!reason && !['restore', 'unban'].includes(action)) return;
    let endsAt: string | undefined;
    if (action === 'ban') { const end = window.prompt('Fecha de fin opcional (AAAA-MM-DD). Déjalo vacío para bloqueo indefinido:')?.trim(); if (end) endsAt = new Date(`${end}T23:59:59`).toISOString(); }
    setBusy(true); setMessage('');
    try { const targetType = action === 'ban' || action === 'unban' ? 'user' : item.targetType; const targetId = action === 'ban' || action === 'unban' ? item.authorUserId : item.id; const response = await fetch('/api/admin/community/moderate', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ targetType, targetId, authorUserId: item.authorUserId, action, reason, endsAt }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? 'No se pudo moderar.'); setMessage('Acción registrada en la auditoría.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo moderar.'); } finally { setBusy(false); }
  }
  return <>
    <section className="admin-community-filters shell panel"><div role="group" aria-label="Estado">{statusOptions.map(([value, label]) => <button type="button" className={status === value ? 'selected' : ''} onClick={() => setStatus(value)} key={value}>{label}</button>)}</div><label>Sección<select value={section} onChange={(event) => setSection(event.target.value)}>{sectionOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Desde<input type="date" value={date} onChange={(event) => setDate(event.target.value)}/></label><label className="admin-check"><input type="checkbox" checked={reported} onChange={(event) => setReported(event.target.checked)}/> Solo reportados</label></section>
    {message && <p className="community-message shell" role="status">{message}</p>}
    <section className="admin-community-list shell" aria-busy={busy}>{busy && !items.length ? <p>Cargando moderación…</p> : items.length ? items.map((item) => <article className={`panel admin-community-item status-${item.status}`} key={`${item.targetType}-${item.id}`}><header><div><span>{item.targetType === 'thread' ? 'Pregunta' : 'Respuesta'}</span><b>{item.authorDisplayName}</b></div><strong>{item.status}</strong></header>{item.title && <h2>{item.title}</h2>}<p>{item.content}</p><div className="community-context-chips"><span>Lección {item.lessonId}</span><span>{sectionLabels[item.section as CommunitySection] ?? item.section}</span>{item.concept && <span>{item.concept}</span>}</div><small>{new Date(item.createdAt).toLocaleString('es-PE')} · {item.reportCount} reportes · {item.actionCount} acciones</small><div className="admin-community-actions"><button type="button" onClick={() => setExpanded(expanded === item.id ? null : item.id)}>Ver conversación / reportes</button>{item.status === 'active' && <button type="button" onClick={() => void moderate(item, 'hide')}>Ocultar</button>}{item.status !== 'active' && <button type="button" onClick={() => void moderate(item, 'restore')}>Restaurar</button>}<button type="button" onClick={() => void moderate(item, 'delete')}>Eliminar lógicamente</button><button type="button" onClick={() => void moderate(item, 'ban')}>Bloquear publicaciones</button><button type="button" onClick={() => void moderate(item, 'unban')}>Quitar bloqueo</button></div>{expanded === item.id && <div className="admin-community-detail"><h3>Reportes recibidos</h3>{item.reports.length ? item.reports.map((report) => <p key={report.id}><b>{reportReasonLabels[report.reason as keyof typeof reportReasonLabels] ?? report.reason}</b>{report.details ? ` · ${report.details}` : ''}<small>{new Date(report.createdAt).toLocaleString('es-PE')}</small></p>) : <p>Sin reportes.</p>}</div>}</article>) : <div className="empty-state panel"><h2>No hay publicaciones en esta vista.</h2><p>La comunidad comienza vacía y no se crean datos ficticios.</p></div>}</section>
  </>;
}
