import Link from 'next/link';
import { SiteShell } from '@/components/SiteShell';
import { SpeakButton } from '@/components/SpeakButton';
import { learningModules } from '@/seed/modules';
import { ARCADE_GAME_COUNT } from '@/data/arcade-games';
import { getCurriculum, scopeDefinitions } from '@/seed/curriculum';

const completeCourse=getCurriculum('l1-l2-l3');
const stats=[[String(completeCourse.vocabulary.length),'Entradas auditadas'],[String(completeCourse.characters.length),'Hanzi curriculares'],[String(ARCADE_GAME_COUNT),'Juegos activos'],['100','Puntos por examen']];

export default function Home(){return <SiteShell><main className="page-main">
  <section className="hero shell"><div className="hero-copy"><p className="eyebrow">基础汉语 · LECCIONES 1–3</p><h1>从认识到家庭</h1><p className="pinyin">Cóng rènshi dào jiātíng</p><p className="translation">De presentarte a hablar de tu familia</p><p className="intro">Una plataforma completa para escuchar, recordar, construir y conversar. Tu progreso se guarda por concepto; tus errores deciden qué vuelve después.</p><div className="hero-actions"><Link className="button button-primary" href="/study/l1-l2-l3/daily">Continuar estudiando <span>→</span></Link><span className="time-note">◷ 10–15 min por sesión</span></div></div><aside className="ink-card"><div className="seal">家</div><p className="ink-kicker">FRASE DE HOY</p><p className="ink-hanzi">你家有几口人？</p><p className="ink-pinyin">Nǐ jiā yǒu jǐ kǒu rén?</p><div className="ink-divider"/><p>¿Cuántas personas hay en tu familia?</p><SpeakButton text="你家有几口人？"/></aside></section>
  <section className="stats shell" aria-label="Alcance del curso">{stats.map(([value,label])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</section>
  <section className="path-section shell"><div className="section-heading path-heading"><div><p className="eyebrow">ELIGE TU ALCANCE</p><h2>Lecciones y repasos acumulativos</h2></div><p>Un solo sistema · contenido separado</p></div><div className="module-grid">{(['l1','l2','l3','l1-l2','l1-l2-l3'] as const).map((scope,index)=><Link className="module-card is-open" href={`/study/${scope}`} key={scope}><span className="module-number">{String(index+1).padStart(2,'0')}</span><div><h3>{scopeDefinitions[scope].label}</h3><p>{scopeDefinitions[scope].description}</p></div><span className="module-state">Abrir</span></Link>)}</div></section>
  <section className="content-grid shell"><article className="today-card"><div className="section-heading"><div><p className="eyebrow">SESIÓN ADAPTATIVA</p><h2>Empieza hoy</h2></div><span className="date-pill">LECCIÓN 1</span></div><p className="muted">Combina recuperación activa, tonos, gramática, hanzi y diálogo en una sesión breve.</p><div className="lesson-list"><div><span className="list-icon jade">复</span><p><b>Repaso espaciado</b><small>Dominio y estabilidad por dimensión</small></p><em>SRS</em></div><div><span className="list-icon amber">错</span><p><b>Errores útiles</b><small>Regla, respuesta y próxima acción</small></p><em>反馈</em></div><div><span className="list-icon red">榜</span><p><b>Meta compartida</b><small>Tu mejor examen en el ranking voluntario</small></p><em>排行</em></div></div><Link className="button button-dark" href="/lesson/1/daily">Abrir sesión de hoy →</Link></article><aside className="focus-card"><p className="eyebrow">TU CAMINO</p><div className="focus-ring"><span>12<small>MÓDULOS</small></span></div><h3>De sonidos a conversación</h3><p>La Lección 1 conserva su ruta original de doce módulos.</p><Link href="/lesson/1">Ver ruta completa →</Link></aside></section>
  <section className="path-section shell"><div className="section-heading path-heading"><div><p className="eyebrow">EXPLORA</p><h2>Ruta de aprendizaje</h2></div><p>11 módulos + examen final</p></div><div className="module-grid">{learningModules.slice(0,8).map(module=><Link className="module-card is-open" href={module.href} key={module.number}><span className="module-number">{String(module.number).padStart(2,'0')}</span><div><h3>{module.title}</h3><p>{module.subtitle}</p></div><span className="module-state">Abrir</span></Link>)}</div></section>
  <section className="cta-band"><div className="shell"><p className="eyebrow">PRIMERA META</p><h2>Sube en el ranking</h2><p>Completa el examen, mejora tu puntuación y participa públicamente solo si tú lo decides.</p><Link className="button button-primary" href="/lesson/1/exam">Ver examen final →</Link></div></section>
</main></SiteShell>}
